
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头

server:
  port: 8089
  servlet:
    context-path: /vehicle #所有访问该应用的路径前缀

spring:
  main:
    allow-bean-definition-overriding: true


  #连接池配置
  datasource:
    name: druidDatasource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vehicle_shop?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 配置测试查询语句, #Oracle需要打开注释
      validationQuery: SELECT 1 FROM DUAL
      # 初始化大小，最小，最大
      initialSize: 10
      minIdle: 10
      maxActive: 200
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  application:
    name: authApp



## soul 配置
soul:
  http:
    adminUrl: http://localhost:9095
    contextPath: /auth
    appName: authApp
    #register: true
    #zookeeperUrl: localhost:2181
  dubbo:
    adminUrl: http://localhost:9095
    contextPath: /auth
    appName: authApp


# mybatis sql日志
#logging:
#  level:
#    org:
#      springframework:
#        boot:
#          #SpringBoot去掉CONDITIONS EVALUATION REPORT及自动配置内容的显示
#          autoconfigure: error
#    com:
#      biao: debug

# 使用logback做日志替换默认日志系统，并指定logback 配置文件地址
logging:
  config: "classpath:config/logback-dev.xml"



# 打印sql到console
mybatis-plus:
  config-location: classpath:config/mybatis-config.xml